# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_trajectory_controller
    - gripper_action_controller

  arm_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    action_ns: follow_joint_trajectory
    default: true
  gripper_action_controller:
    type: GripperCommand
    joints:
      - left_gripper_finger_joint
      - right_gripper_finger_joint
    action_ns: gripper_cmd
    default: true

trajectory_execution:
  execution_duration_monitoring: false
  allowed_start_tolerance: 0.01
  trajectory_execution_manager:
    execution_type: "simple"
  trajectory_smoother:
    type: "ruckig"

